osx_image: xcode9
language: objective-c
xcode_sdk: iphonesimulator10.0

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS

script:
- set -o pipefail
- travis_retry xcodebuild -project Presentation.xcodeproj -scheme "Presentation-iOS" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
